apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden-ingress
  namespace: farhoodliquor-com
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect@kubernetescrd
spec:
  ingressClassName: traefik-external
  rules:
  - host: passwords.farhoodliquor.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  vaultwarden
            port:
              number: 80

  tls:
  - hosts:
    - passwords.farhoodliquor.com
    secretName: farhoodliquor-com-cert-letsencrypt-prod