apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik-external
  rules:
  - host: passwords.farhoodliquor.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  vaultwarden
            port:
              number: 80
  tls:
  - hosts:
    - passwords.farhoodliquor.com
    secretName: passwords.farhoodliquor.com-cert