
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: farhoodliquor-com
#secretGenerator:
#- name: application-pass
#  literals:
#  - password=somepassword
resources:
  - volumes.yaml
  - service.yaml
  - ingress.yaml