
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - volumes.yaml
  - service.yaml
  - ingress.yaml
  - statefulset.yaml
  - sealedsecret-vaultwarden-env.yaml
#  - volumes.yaml # this was created outside of fluxcd