---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: farhoodliquor-com
  name: bitwarden-pv
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi