apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-env
  namespace: vaultwarden
type: Opaque
data:
  SMTP_PORT: NTg3
  SMTP_HOST: ZW1haWwtc210cC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbQ==
  SMTP_USERNAME: 
  SMTP_PASSWORD: 
  SMTP_FROM: bm8tcmVwbHlAZmFyaC5uZXQ=
  SMTP_SECURITY: c3RhcnR0bHM=
  ADMIN_TOKEN:
