---
apiVersion: v1
kind: Service
metadata:
   name: vaultwarden
   namespace: farhoodliquor-com
   labels:
     app: vaultwarden
spec:
  clusterIP: None
  #type: LoadBalancer
  #externalTrafficPolicy: Local
  ports:
  - port: 80
  selector:
    app: vaultwarden
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden
  namespace: farhoodliquor-com
spec:
  selector:
    matchLabels:
      app: vaultwarden
  serviceName: "vaultwarden"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: vaultwarden
        image: docker.io/vaultwarden/server:latest
        imagePullPolicy: Always
        env:
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: vaultwarden-env
              key: SMTP_PORT
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: vaultwarden-env
              key: SMTP_HOST
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: vaultwarden-env
              key: SMTP_USERNAME
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vaultwarden-env
              key: SMTP_PASSWORD
        - name: SMTP_FROM
          valueFrom:
            secretKeyRef:
              name: vaultwarden-env
              key: SMTP_FROM
        - name: SMTP_SECURITY
          valueFrom:
            secretKeyRef:
              name: vaultwarden-env
              key: SMTP_SECURITY
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: vaultwarden-env
              key: ADMIN_TOKEN
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: vaultwarden-config
          mountPath: "/data"
        - name: temp
          mountPath: "/temp"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: vaultwarden-config
        persistentVolumeClaim:
          claimName: vaultwarden-config
      - name: temp
        nfs:
          server: spielberg.farhoodliquor.dmz
          path: /mnt/pool0/backups/temp