---
apiVersion: v1
kind: Service
metadata:
   name: vaultwarden
   namespace: farhoodliquor-com
   labels:
     app: vaultwarden
spec:
  clusterIP: None
  #type: LoadBalancer
  #externalTrafficPolicy: Local
  ports:
  - port: 80
  selector:
    app: vaultwarden
