---
apiVersion: v1
kind: Service
metadata:
   name: vaultwarden
   namespace: farhoodliquor-com
   labels:
     app: vaultwarden
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: vaultwarden