apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden
spec:
  selector:
    matchLabels:
      app: vaultwarden
  serviceName: "vaultwarden"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: vaultwarden
        image: docker.io/vaultwarden/server:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: vaultwarden-env
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
#        - name: vaultwarden-config
#          mountPath: "/data"
        - name: config
          mountPath: "/data"
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
#      volumes:
#      - name: vaultwarden-config
#        persistentVolumeClaim:
#          claimName: vaultwarden-config
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi