---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-config
  labels:
    name: bitwarden-config
  namespace: mediaserver
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi