---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config
  labels:
    name: vaultwarden-config
  namespace: farhoodliquor-com
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-temp
  labels:
    name: vaultwarden-temp
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/sites/passwords-farhoodliquor-com/
    server: spielberg.farhoodliquor.dmz