---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config
  labels:
    name: vaultwarden-config
  namespace: farhoodliquor-com
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: rook-ceph-block-nvme
  resources:
    requests:
      storage: 8Gi