---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config
  labels:
    name: vaultwarden-config
    kustomize.toolkit.fluxcd.io/prune: disabled
  namespace: farhoodliquor-com
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-perpetual
  resources:
    requests:
      storage: 8Gi